
version: '3'                                

services:                                   
  db:  
    build:
        context: ./mysql
    command: --innodb-use-native-aio=0      
    container_name: db                      
    restart: always                         
    tty: true                               
    volumes:                                
        - ./mysql-volume:/var/lib/mysql     
    networks:                               
        - nginx-node-network                

  app:
    build:
        context: ./node
    container_name: app    
    networks:
        - nginx-node-network
    volumes:  # volumes
        - ./node:/usr/src/app/
        - exclude:/usr/src/app/node_modules/
    tty: true
    ports:  # configura a porta
        - "3000:3000"

    depends_on:
        - db

  proxy:
    build:
        context: ./nginx
    container_name: proxy
    networks:
        - nginx-node-network
    tty: true
    ports:  # configura a porta
        - "8080:80"
    depends_on:
        - app

networks:                                   # configuracao das redes
  nginx-node-network:                       # nome da rede
    driver: bridge                          #tipo da rede

volumes:
    exclude: